name: Npm tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "**/main"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      # This actually doesn't work from a forked repo so ignoring for now
      # with:
      #   ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
      # This actually doesn't work from a forked repo so ignoring for now
      # - name: Push yarn.lock update
      #   run: |
      #     git config --global user.email "bam.flashlight@gmail.com"
      #     git config --global user.name "flashlight-bot"
      #     git add yarn.lock && git diff --staged --quiet || git commit -m "chore: update yarn.lock"
      #     git push
